dist: trusty
sudo: required  #Docker runs as root, permissions are needed

language: node_js
node_js:
  - '12.16.2'

env:
  global:
  - secure="ch0HHa5BxOJXhgucblWzUI1jnKhRTj/fOmgvb0itANRdNdeVUUJo1XH6If8gxm71fiyaEnZPKvzYr71PrxxUKp48GyzX7k/jpCwWSWnUrZev7pvc2kpF2JUkl6WnXAps3wVMCzwoL+oA7cQd9yiBtysBOqPr52xTzBX5rnt8chIK8Q+u/MUCvnDoe7k+KHontbofYKaFd+9khbx7NSQlDBvxDfykGwm/U8vHrYwF0V2zd6OPAB7/l4mETObwi2J0HEwNwg9R+aW+gSzIKpIDJedkgqKDUR6D8IcJo8143FywmDajK2us2s8+I1L21jTmySuQ5ML1plfpBXBIPRXJKzsmhvz4AlwaVI7AONuDHdOruR3UP2T8NO9IcaCLahaBbTcx0NJ6rtm+JFQX8ZAybtGZWJDSSCI0nX+tjhFlHV8CkO54p12LuIQ7gWE2jDnYBRIan1YoKgAQuYC+nlEKNzmJOp6JmwJSp14plKt9S0EVSeRBmhnHMD9PvrmycdqVGIBnAQ4rTzClxPwGp16YMRpHnbOxTRpelYECKOAJf/xrQNLHqIVQokIloEPMCedVJtNOdh5fDXLYaRa7nSfN1hGLE9VRCJsLSyhY0+dkOy9XSO54m9jFI+V9qfoINY8wi3+UVenss5kGci59SuzaoHCVCrcp75wZ3OpvG34ucuA="
  - secure="h3HWltg6MUOKOzL2dkESfnYUmNWBuNc/WcfXzlLNb8bGAActIIfAUqLWSj/4Tiio5/ZjjrCGFsfjRm7TwemyMIYqwRveKMHJbHvekaOSL1J7WBh1g2KqKoyubyAUJBnQVft9etz2ZjjwtKM6vPJb0Q9bxPfVlXV1JESkQYkd2lBBI2F82dDCY8JTc084Ty2doF6NTmy9YMT5mil+HSl2ujDFgbjFMY+iaQQ/iMkQUv4MDBN+rXs2SsMMHBhdXgzAblvFUsh1kSIYc9J3Ly5DfZ2zj1+5uJE14cIyT+ItkbRVAqaVcoMoqpDSiV1IbxqXNYECC838l3iqmubbymMDou2v/eMO4xMUPl76fW+aykx6ss8mtVz3vdBbQKy22F2KgOh9eHKcfdVzAmFsq4xARf7yI3PKeA94yDfiGLWXHSuLEj4ZuIoMTzHG0dGpxZB1lU2jCy9SBSvTKoB6MwM0AcwfWviVVxgyG1j4/wbTM9OF7TkMKqj7mMpoevStu+ugrKiSFC2BXB7zGwjuOJf0jPcprxBJjFGdH3UMGGOv4MfJfvB86XJj8tn6Nd0Gp1ZmSEj60ws7puDWWtCVq7gp0ELIr541ujasllQjlm4aRZwlYS6DgMPBY+w91ZwzL5Gf7qLaONDL9AfFh3AK88/f53AtJNIdrJKzQ1bVecGlY+c="

addons:
  chrome: stable

services:
  - docker

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
     - ./node_modules

before_script:
  - npm install

script:
  #- npm run test -- --watch=false
  #- npm run e2e
  - docker build -t tacs-grupo3-front_end .

after_success:
  - docker login -u $USERDOCKER -p $PASSWORDDOCKER
  - docker tag tacs-grupo3-front_end $USERDOCKER/tacs-grupo3-front_end:$TRAVIS_BUILD_NUMBER
  - docker push $USERDOCKER/tacs-grupo3-front_end:$TRAVIS_BUILD_NUMBER
  - docker tag tacs-grupo3-front_end $USERDOCKER/tacs-grupo3-front_end:latest
  - docker push $USERDOCKER/tacs-grupo3-front_end:latest
