dist: trusty
sudo: required  #Docker runs as root, permissions are needed

language: node_js
node_js:
  - '12.16.2'

env:
  global:
    - secure="chIesLzEttNOOLFUkyyA8XQqHRZpPGytmRLFuzLenSHg19kPrvu//UXGqQtig6OdxGhtq59tv7uxxdplrbU7WO1Z8qPucf3LTvqLJBMdaqlzNvZwgIJPG9AeX3sQwQ/mVYnjcp0h2MCQQajsJ0jAG8TNH6ySnsBXTOUmrHB0kOQOelrNqyoFLhGuBg8vjVtvd9MZ4cecJxW87RzGtN7E2w6zOrmrzWRu/f6c6fMC3AuucvzdnMql7FYLZEd+vTKCdsHMWlLnlIWonIdHMROSI9H+niZUpx4tDc3B0LKRBaiXI29Db28hSzOrYSF+A2OaoWkoZqHlLdylxh9CAVa2RvWMRrTXM2WIoFXOeRKW6rOaWXRl0jkXLzchrqrabh8FExUVEuG9tHY0g3IU35uKQyEnmFx3xa7sD6nD+j8rg+OjfZ71Z4KXnH1cWMdehj4bgNTopQjBtGcYjJIJsW0yFJWOeiYPcwKl3BWJSsq6v2e0bYKWOTdSqH735J6k6kzZGrUJTm706kc8KLdK4/yoO03qefgeUciYbBpTh/O1zuYEmKYbGmq5HoOZRD7x5G2daLF1mQNNwmP/d5axZn1EhOIAbRl4rnyoUH2+wMXaPRCsjZyJK/z/LDttHNoiIV+JcbXrIG86F7960hxkUy0A+D04uDeIt2DL0sAeyh6/Pj4="
    - secure="biDdL37Iur9klkqG1tany2f3ovg2Tkt9j4B5Ohv7ZSTrfRpd3paD13QSgIbzG+72fXj7pVv2oxXgtpca5ARMbSmP149+vQ652B0tw/PpXXWSHGFRorU+UepPOB5NImARG5f9pIzlteZPsnkd5wxVP+B7jj9hwq4oeVD2E1l7aloJZ6KZDbDOBe7gq88/Bo9EG0Sn9lBJnA3x5tgQRKCBiaj+WuLvIihmS+5xA/xNiuncOjnMq8MRETMRetJ7Gxzc+Fn05cIqW8l1vDiWZYDhaTOubuMhP4xPEdbEEcnZC1WF/xbqYYh8iSEZF9qVUCviqUtHQZ5kIfz4GS6Nw+Ub42fJFscwrfbzMhB2CmqzQASsUN+fuvZKj553WtJuivoLT04jtYkOpzE9g30pPjMAGOonJas7c7xtsPKo+Gfrj5RcXmYzf8jBQ15mNr/BeM5JrSfBHlfxTTNt50mPoqukoP7GTdbv0GvE8VECuliffq2fCS6MphcydyjfDaVpswtU/g+7Qel0tTn61HNwwJXUeNeF7t8Kz3squmvfysLzK6iA7f/NAzJTjuHszZpfNXNWJgCqjLFuhalZ3hfePK/hIXPVe93LbAkLKtZBb5tnUtM1gVp83e0Nd50gVndR6gqPZTL4ObDrHuGZFpX2ucegixIMaNBHyC9of25ljk+4M0A="

addons:
  chrome: stable

services:
  - docker

before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
     - ./node_modules

jobs:
  include:
    - stage: build docker image and deploy
      if: tag IS present
      script:
      - docker build -t tacs-grupo3-front_end .
      - docker login -u $USERDOCKER -p $PASSWORDDOCKER
      - docker tag tacs-grupo3-front_end $USERDOCKER/tacs-grupo3-front_end:$TRAVIS_BUILD_NUMBER
      - docker push $USERDOCKER/tacs-grupo3-front_end:$TRAVIS_BUILD_NUMBER
      - docker tag tacs-grupo3-front_end $USERDOCKER/tacs-grupo3-front_end:latest
      - docker push $USERDOCKER/tacs-grupo3-front_end:latest
